// Emits TypeScript declaration files for compiled .ur modules, so TS code
// (and editors) consuming UrLang output get real types. Dependency-free.
import type { ModuleExports } from "./checker.js";
import type { Type } from "./types.js";

function tsName(t: Type, parenthesizeUnion = false): string {
  switch (t.kind) {
    case "adad": return "number";
    case "lafz": return "string";
    case "bool": return "boolean";
    case "koi": return "any";
    case "khaali": return "null";
    case "kuchnahi": return "void";
    case "literal": return typeof t.value === "string" ? JSON.stringify(t.value) : String(t.value);
    case "array": {
      const inner = t.element.kind === "union" || t.element.kind === "function"
        ? `(${tsName(t.element)})`
        : tsName(t.element);
      return `${inner}[]`;
    }
    case "union": {
      const s = t.members.map((m) => tsName(m, true)).join(" | ");
      return parenthesizeUnion ? s : s;
    }
    case "wada": return `Promise<${tsName(t.value)}>`;
    case "object": {
      if (t.props.size === 0) return "{}";
      const parts: string[] = [];
      for (const [k, p] of t.props) parts.push(`${k}${p.optional ? "?" : ""}: ${tsName(p.type)}`);
      return `{ ${parts.join("; ")} }`;
    }
    case "function": return fnTsSignature(t, "=>");
    case "typeParam": return t.name;
    case "class": return t.name;
  }
}

function fnParams(t: Extract<Type, { kind: "function" }>): string {
  const parts = t.params.map((p, i) => `arg${i}${i >= t.requiredParams ? "?" : ""}: ${tsName(p)}`);
  if (t.restParam !== null) parts.push(`...rest: ${tsName(t.restParam)}[]`);
  return parts.join(", ");
}

function fnTsSignature(t: Extract<Type, { kind: "function" }>, style: "=>" | ":"): string {
  const tp = t.typeParams.length > 0 ? `<${t.typeParams.join(", ")}>` : "";
  const sep = style === "=>" ? " => " : ": ";
  return `${tp}(${fnParams(t)})${sep}${tsName(t.returnType)}`;
}

function classDecl(name: string, t: Extract<Type, { kind: "class" }>, prefix: string): string {
  const lines: string[] = [`${prefix}declare class ${name} {`];
  const ctorParams = t.ctorParams
    .map((p, i) => `arg${i}${i >= t.ctorRequired ? "?" : ""}: ${tsName(p)}`)
    .join(", ");
  lines.push(`  constructor(${ctorParams});`);
  if (t.instance.kind === "object") {
    for (const [k, p] of t.instance.props) {
      if (p.type.kind === "function") {
        lines.push(`  ${k}${fnTsSignature(p.type, ":")};`);
      } else {
        lines.push(`  ${k}${p.optional ? "?" : ""}: ${tsName(p.type)};`);
      }
    }
  }
  lines.push("}");
  return lines.join("\n");
}

/** Renders a module's export surface as .d.ts text. */
export function emitDts(exports: ModuleExports): string {
  const lines: string[] = ["// Generated by urlang — TypeScript declarations for a .ur module."];
  for (const [name, t] of exports.types) {
    lines.push(`export type ${name} = ${tsName(t)};`);
  }
  for (const [name, t] of exports.values) {
    if (t.kind === "function") {
      lines.push(`export declare function ${name}${fnTsSignature(t, ":")};`);
    } else if (t.kind === "class") {
      lines.push(classDecl(name, t, "export "));
    } else {
      lines.push(`export declare const ${name}: ${tsName(t)};`);
    }
  }
  if (exports.defaultType !== null) {
    lines.push(`declare const _default: ${tsName(exports.defaultType)};`);
    lines.push("export default _default;");
  }
  return lines.join("\n") + "\n";
}
